OrangeHRM_URL=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

validLoginUsername=Admin
#validLoginPassword=admin123
#encrypted password
validLoginPassword=NUKUms5zgbOo4lX1wqZ9eQ==

invalidLoginUsername=wronguser
#invalidLoginPassword=wrongpass
#encrypted password
invalidLoginPassword=C2TfABv5ecGK1NyUwLhG4w==